spring:
  application:
    name: URL-Shortening-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/URL
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
